Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using TaskManagerUI.Models;


namespace TaskManagerUI.Controllers
{
    public class ProjectController : Controller
    {
        private readonly Uri _baseAddress = new Uri("https://localhost:7293/api");
        private readonly HttpClient _client;
        private string JwtToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3QyIiwibmFtZWlkIjoiMjAwMyIsIm5iZiI6MTcxNjgzMjI1MywiZXhwIjoxNzE2ODc1NDUzLCJpYXQiOjE3MTY4MzIyNTN9.pe9dFVwolOIQiE3nI7A-urOF78UU8gl7ejE5vvENyWE";

        public ProjectController()
        {
            _client = new HttpClient();
            _client.BaseAddress = _baseAddress;
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JwtToken);
        }

        [HttpGet]
        public IActionResult Index(int page = 1)
        {
            PageResultViewModel<ProjectViewModel> pagedResult = new PageResultViewModel<ProjectViewModel>();
            HttpResponseMessage response = _client.GetAsync($"{_client.BaseAddress}/Projects?page={page}&pageSize=15").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                pagedResult = JsonConvert.DeserializeObject<PageResultViewModel<ProjectViewModel>>(data);
            }
            else
            {
                Console.WriteLine($"Request failed with status code: {response.StatusCode}");
            }
            return View(pagedResult);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProjectViewModel project)
        {
            try
            {
                if (project == null)
                {
                    return View("Error");
                }
                project.Tasks = new List<TaskViewModel>();
                string data = JsonConvert.SerializeObject(project);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage reponse = _client.PostAsync(_client.BaseAddress + "/Projects/PostProject", content).Result;
                if (reponse.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Project Created.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                ProjectViewModel project = new ProjectViewModel();
                project.Id = id;
                project.Tasks = new List<TaskViewModel>();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Projects/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    project = JsonConvert.DeserializeObject<ProjectViewModel>(data);
                }

                return View(project);
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(ProjectViewModel model)
        {
            try
            {
                model.Id = model.Id;
                model.Tasks = new List<TaskViewModel>();
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + $"/Projects/{model.Id}", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Project details updated.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                ProjectViewModel project = new ProjectViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Projects/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    project = JsonConvert.DeserializeObject<ProjectViewModel>(data);
                }

                return View(project);
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + $"/Projects/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Project deleted.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }

            return View();
        }

        [HttpGet]
           public IActionResult Search(string name)
           {
               List<ProjectViewModel> projects = new List<ProjectViewModel>();

               HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Projects/{name}").Result;

               if (response.IsSuccessStatusCode)
               {
                   string data = response.Content.ReadAsStringAsync().Result;
                   projects = JsonConvert.DeserializeObject<List<ProjectViewModel>>(data);
               }
               else
               {
                   Console.WriteLine($"Request failed with status code: {response.StatusCode}");
               }
               return View(projects);
           }
    }
}

Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using TaskManagerUI.Models;

namespace TaskManagerUI.Controllers
{
    public class TaskController : Controller
    {
        private readonly Uri _baseAddress = new Uri("https://localhost:7293/api");
        private readonly HttpClient _client;
        private string JwtToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3QyIiwibmFtZWlkIjoiMjAwMyIsIm5iZiI6MTcxNjgzMjI1MywiZXhwIjoxNzE2ODc1NDUzLCJpYXQiOjE3MTY4MzIyNTN9.pe9dFVwolOIQiE3nI7A-urOF78UU8gl7ejE5vvENyWE";

        public TaskController()
        {
            _client = new HttpClient();
            _client.BaseAddress = _baseAddress;
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JwtToken);
        }

        public IActionResult Index(int page = 1)
        {
            PageResultViewModel<TaskViewModel> pagedResult = new PageResultViewModel<TaskViewModel>();
            HttpResponseMessage response = _client.GetAsync($"{_client.BaseAddress}/Tasks?page={page}&pageSize=15").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                pagedResult = JsonConvert.DeserializeObject<PageResultViewModel<TaskViewModel>>(data);
            }
            else
            {
                Console.WriteLine($"Request failed with status code: {response.StatusCode}");
            }
            return View(pagedResult);
        }

        /*public IActionResult Index()
        {
            List<TaskViewModel> tasks = new List<TaskViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Tasks").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                tasks = JsonConvert.DeserializeObject<List<TaskViewModel>>(data);
            }
            else
            {
                Console.WriteLine($"Request failed with status code: {response.StatusCode}");
            }
            return View(tasks);
        }*/

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TaskViewModel task)
        {
            try
            {
                if (task == null)
                {
                    return View("Error");
                }
                string data = JsonConvert.SerializeObject(task);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage reponse = _client.PostAsync(_client.BaseAddress + "/Tasks/PostTask", content).Result;
                if (reponse.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Task Created.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                TaskViewModel task = new TaskViewModel();
                task.Id = id;
                task.UserTasks = new List<UserTaskViewModel>();
                task.Project= new ProjectViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Tasks/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    task = JsonConvert.DeserializeObject<TaskViewModel>(data);
                }

                return View(task);
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(TaskViewModel model)
        {
            try
            {
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + $"/Tasks/{model.Id}", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Task details updated.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                TaskViewModel task = new TaskViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + $"/Tasks/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    task = JsonConvert.DeserializeObject<TaskViewModel>(data);
                }

                return View(task);
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + $"/Tasks/{id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Task deleted.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagerUI.styles.css" asp-append-version="true" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task Manager</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                    </li><li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @{
            var errorMessage = TempData["errorMessage"]?.ToString();
            var successMessage = TempData["successMessage"]?.ToString();
        }
        @if (!string.IsNullOrWhiteSpace(@successMessage))
        {
            <div class="alert alert-success">
                <b>Success: </b>@successMessage
                <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
        else if (!string.IsNullOrWhiteSpace(@errorMessage))
        {
                <div class="alert alert-danger">
                    <b>Error: </b>@errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
        }
    </main>
</div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskManagerUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>